export let commands = {
    GET_ID: [0x01, "UNICAST", 1],
    INITIALIZE: [0x02, "UNICAST", 13],
    GET_VERSION: [0x03, "UNICAST", 1],
    MOVE_FEED_FORWARD: [0x04, "UNICAST", 2],
    MOVE_FEED_BACKWARD: [0x05, "UNICAST", 2],
    MOVE_FEED_STATUS: [0x06, "UNICAST", 1],
    VENDOR_OPTIONS: [0xbf, "UNICAST", 0],
    GET_FEEDER_ADDRESS: [0xc0, "BROADCAST", 13],
    IDENTIFY_FEEDER: [0xc1, "BROADCAST", 13],
    PROGRAM_FEEDER_FLOOR: [0xc2, "BROADCAST", 14],
    UNINITIALIZED_FEEDERS_RESPOND: [0xc3, "BROADCAST", 1]
};